### ISSUE TITLE
Simple CMS: Add possibility for different page templates

### ISSUE THREAD

**Issue by juhakujala** [shuup/shuup#1246]
Currently there's only one template that can be used with simple cms pages (page.jinja). It would be great if it was possible to create multiple template files under the simple cms directory and define the templates in e.g. settings file.

**Comment by maximlion** [comment]
@tulimaki Should a user have the possibility to use more than one template `at the same time` or should we limit the user to using just one template(whichever he chooses to use)?

**Comment by maximlion** [comment]
@juhakujala Since Shuup now supports per page placeholders this shouldn’t be needed. By leaving title and content empty the merchant has option to add content through placeholders and this way decide whatever structure or style per page. Instead we will improve these options and add some help texts about this for the merchant and we didn’t fully understand the need for this anymore since the per page placeholders should help with this. Actual page template (page.jinja) can still be changed per theme to fit the contents and placeholders for the theme. Placeholders can also be page-specific or global.

**Comment by juhakujala** [comment]
@maximlion Thank you for the answer. I still see this as a valid issue since there might be a need to change the whole layout of CMS pages.

Here's an example:
Let's say that my theme has a sidebar block defined in `base.jinja` and for some CMS pages I want to have it displayed. I could go with `page.jinja` and have that sidebar block untouched. But then on some CMS pages I want to hide that sidebar from the template to get 100% wide content so then I would have another template called e.g. `page_no_sidebar.jinja`. And in that template I would hide the sidebar by adding an empty sidebar block.

**Comment by chessbr** [comment]
@juhakujala yes, I agree with you. However, I think this should be done for all template pages, not only for CMS. IMO, this could be introduced in a new Shuup tool to design templates dynamically, which we are already talking about. We are going to "try" making this better. The only possible solution would be adding the extra content (or even scripts/styles) though xtheme injection, like GDPR does, but it will require some extra coding to match which pages should have the code injected.
Anyways, that PR wouldn't complete solve the issue until we have some more advanced template design editor.

**Comment by tulimaki** [comment]
@juhakujala you are right. Option for per page templates will be included to that PR related to this issue.

**Comment by chessbr** [comment]
Done in https://github.com/shuup/shuup/pull/1459
