### ISSUE TITLE
Django 1.8 is no longer supported (?)

### ISSUE THREAD

**Issue by igordavydsson** [shuup/shuup#1396]
This [migration file](https://github.com/shuup/shuup/blob/master/shuup/front/apps/carousel/migrations/0003_add_shops.py#L13) fails on Django 1.8.

Used there `set()` method was added only in Django 1.9 ([changelog source](https://docs.djangoproject.com/en/2.0/releases/1.9/#related-set-direct-assignment))

So, when shuups `setup.py` says that [Django 1.8 is enough](https://github.com/shuup/shuup/blob/master/setup.py#L88) it is kinda misleading.

**Comment by tulimaki** [comment]
I wouldn't recommend using Django 1.8 with any new project and highly recommend you update your existing projects too.

But answer your question is yes. We still run tests for Django 1.8 while merging new code and since we add unit tests pretty much to all new code I would guess the Shuup actually work with Django 1.8 too.

And yes that migration from 0002 to 0003 in carousel app has a bug. Seems to be pretty much only misplaced set, but I can't guarantee this is only issue with Django 1.8.

**Comment by tulimaki** [comment]
Fix for this is now merged and this is included to next smaller release which will be around Wednesday.
