### ISSUE TITLE
Able to pin Django 1.11.18 instead?

### ISSUE THREAD

**Issue by jonovate** [shuup/shuup#1740]
Are we able to move pinned Django from 1.11.16 to 1.11.18 instead?  The big driver here is 1.11.17 brings in official Py3.7 support.

**Comment by tulimaki** [comment]
Updated the latest requirements here [0f6f50b](https://github.com/shuup/shuup/commit/0f6f50b2e29027508d4ee1bdefab20cec7b550fa).

Not sure if these requirements should be used much since for development you should likely just use `pip install -e .[everything]` and for projects you should run Shuup through Django-project for example like here https://github.com/shuup/shuup-project-template.

But will be keep these updates as part of the new releases.
