### ISSUE TITLE
Order Total is not correct after editing when previously editing another order

### ISSUE THREAD

**Issue by sicksid** [shuup/shuup#1947]
Hey guys i have this problem in production, im using version `1.9.3` and after editing a few orders, one of them will have some of the previously edited items and the total will be wrong, here are some screenshots:
![before error](https://user-images.githubusercontent.com/7379966/59307523-4b552400-8c64-11e9-82b0-314fcd3f25ca.png)
![error](https://user-images.githubusercontent.com/7379966/59307524-4b552400-8c64-11e9-8f8b-c9f765a7550b.png)

i hided some information as we use real data sometimes in local...

**Comment by sicksid** [comment]
Here is how i replicate:

1.- edit one order and add items
2.- save
3.- edit another order and sometimes randomly you will have a wrong total

**Comment by tulimaki** [comment]
Seems like redux state from the previous orders are inflated incorrectly. We will take a closer look but meanwhile you can reset the order editor state with the "Discard changes"-button (see screenshot).

![Screen Shot 2019-06-11 at 3 24 32 PM](https://user-images.githubusercontent.com/4940349/59311222-9d467b80-8c5d-11e9-95ed-348f984e5260.png)

Looks like the numbers in the confirmation matches on what the order has so it seems the issue is in the editor itself.

**Comment by tulimaki** [comment]
@sicksid see the fix here. It looks like it works better this way. At least after could not reproduce the issue.

Please let me know if the helps or not.

We will do some more tests around this order editor before next release.

**Comment by sicksid** [comment]
thanks ill give it a try
