### ISSUE TITLE
bitcoin and paypal feature

### ISSUE THREAD

**Issue by jujes** [shuup/shuup#477]
Hi, some information about this features? 
if possible embed now as plugin or where is this branch addons?
thanks in advance :)

**Comment by suutari-ai** [comment]
Hi!

It's possible to create an addon for payment processors, but we don't have bitcoin or paypal addons yet.

If you want to implement a payment processor addon, there is couple addons you could use as an example: https://github.com/shoopio/shoop-stripe/tree/refactor-for-shoop-4 or https://github.com/shoopio/shoop-checkoutfi for examples. Note that the service API has changed in Shoop master since 3.0 release. The new API is shortly documented at http://shoop.readthedocs.io/en/latest/services.html

**Comment by SalahAdDin** [comment]
What's about this feature today?

**Comment by simo97** [comment]
Hi, What about this feature today ?
